# Site settings
title: Z-Pack
email: Zeus@mtOlympus.com
description: > # this means to ignore newlines until "baseurl:"
  The Z-Pack is the ultimate travel neccesity.
baseurl: "nikopj.github.io" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username: 
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown